[project]
name = "anno"
version = "0.1.0"
description = "Project to build anno dependencies"
authors = ["Silen Wang <qiumin14@163.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
# post_install = 'R -e "BiocManager::install(\"rols\")"'

[environments]
default = ['base']

[feature.base.dependencies]
python = '*'
snakemake = "*"
snakemake-storage-plugin-ftp = '*'
snakemake-storage-plugin-http = '*'
scanpy = '*'
openpyxl = '*'
ipykernel = '*'
pixi-kernel = '*'
r-irkernel = "*"
r-base = "*"
r-dplyr = "*"
r-Seurat = "*"
r-HGNChelper = "*"
r-openxlsx = "*"
'r-data.table' = "*"
r-egg = "*"
r-ggplot2 = "*"
r-ggsci = "*"
r-Matrix = "*"
r-psych = "*"
r-RColorBrewer = "*"
r-reshape2 = "*"
r-anndata = "*"
r-hdf5r = "*"
r-BiocManager = "*"
bioconductor-SingleR = "*"
bioconductor-SingleCellExperiment = "*"
r-reticulate = "*"
bioconductor-rols = "*"
'bioconductor-org.Hs.eg.db' = "*"

[feature.base.tasks]
rlang_post_install = {cmd = "Rscript -e 'BiocManager::install(\"GenomeInfoDbData\");BiocManager::install(\"celldex\");hpca.se <- celldex::HumanPrimaryCellAtlasData()'"}